{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.905.0 (24.05)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Clientes\",\"Pedidos\",\"Produtos\",\"Vendas\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "0fd71417-6829-4c9c-8f7a-eff081649a91",
        "fromColumn": "Data Pedido",
        "fromTable": "Pedidos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4d8febcb-1bed-4c8c-938d-d9416fab50cc"
      },
      {
        "name": "e16f2b2f-7761-40f8-96ba-00db024741a6",
        "fromColumn": "Data Envio",
        "fromTable": "Pedidos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_535664b9-f58a-470b-b411-0ab91c57cfa9"
      },
      {
        "name": "AutoDetected_e098636d-7925-4a22-9fd1-d8f410c5aa6c",
        "fromColumn": "Cliente",
        "fromTable": "Vendas",
        "toColumn": "ID Cliente",
        "toTable": "Clientes"
      },
      {
        "name": "fc884bb8-c841-6445-9dbc-b37a758ec4f2",
        "fromColumn": "Produto",
        "fromTable": "Vendas",
        "toColumn": "ID Produto",
        "toTable": "Produtos"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Clientes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2910665-1507-4367-a749-b2662448809a",
            "sourceColumn": "ID Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e097abf1-68f6-4c2e-9b3b-d9f0b962b2ef",
            "sourceColumn": "Nome Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Segmento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbc05297-4cb6-409e-957e-5cba77eb162a",
            "sourceColumn": "Segmento",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c05bf61-fc85-403a-850d-6c4fd1a78290",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9c5d714-10bc-4019-b5d4-03c1eadbd854",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Pais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99d12c0c-9f1e-4ee5-afe4-3a9fc16bb833",
            "sourceColumn": "Pais",
            "summarizeBy": "none"
          },
          {
            "name": "Mercado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d00ddc3-58b0-4f90-8970-991c7d2585f4",
            "sourceColumn": "Mercado",
            "summarizeBy": "none"
          },
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2975dec4-7c11-4b03-a7e1-9a2b6f46bdad",
            "sourceColumn": "Regiao",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f9c33bcc-01a0-47e1-93e0-c0d12c542dba",
        "partitions": [
          {
            "name": "Clientes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"D:\\Marcelo Data\\Data_Science_Academy\\PowerBI Para Business Intelligence e Data Science\\3- Modelagem Relacionamentos e DAX\\Clientes.csv\"),[Delimiter=\";\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
                "    #\"Usar Primeira Linha como Cabeçalho\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID Cliente\", type text}, {\"Nome Cliente\", type text}, {\"Segmento\", type text}, {\"Cidade\", type text}, {\"Estado\", type text}, {\"Pais\", type text}, {\"Mercado\", type text}, {\"Regiao\", type text}})",
                "in",
                "    #\"Usar Primeira Linha como Cabeçalho\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9c0dbba6-1752-4303-aa30-60aabaf98ddf",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4f812519-0cde-4c7b-b4c7-a0d5a86e2619",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1c2a8bf7-f764-45cd-bc83-7f93905c8503",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6c1fc82c-2be7-4916-97e2-76d57bf52278",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "236f017e-b7f1-4526-b834-fba61e486b18",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f1106b2b-08d8-473c-83ae-cc8ada2312e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cd4fc70d-abd3-4f40-b61d-338dedd79175",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cfd73535-9b9d-4ada-a14e-9a8e4348c638",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "0cda0f70-63b6-491e-bfa9-54e1da94fa95",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d979a277-371d-4cd9-a7f5-e7c25027d947",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "3a782f34-1834-4399-b80a-fa313c73bd32",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "ed4c96ca-5ebd-41b5-b1d9-697b8b57b3cc",
                "ordinal": 3
              }
            ],
            "lineageTag": "73587f73-61da-47c7-a078-c9e80f63b48b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e413ee06-8f0a-4e04-9b19-a517c0a56229",
        "partitions": [
          {
            "name": "DateTableTemplate_9c0dbba6-1752-4303-aa30-60aabaf98ddf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Pedidos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "791a0d4c-696f-41c6-9e77-e2eb143a4a90",
            "sourceColumn": "ID Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Data Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "12af36f0-51a7-4ba4-8196-e544d6f31e6a",
            "sourceColumn": "Data Pedido",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_4d8febcb-1bed-4c8c-938d-d9416fab50cc"
                },
                "isDefault": true,
                "relationship": "0fd71417-6829-4c9c-8f7a-eff081649a91"
              }
            ]
          },
          {
            "name": "Data Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f25e429e-6773-454e-95f4-dc29677ebf9a",
            "sourceColumn": "Data Envio",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_535664b9-f58a-470b-b411-0ab91c57cfa9"
                },
                "isDefault": true,
                "relationship": "e16f2b2f-7761-40f8-96ba-00db024741a6"
              }
            ]
          },
          {
            "name": "Modo Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "475f24f4-ce98-4180-a37f-9852ba285c64",
            "sourceColumn": "Modo Envio",
            "summarizeBy": "none"
          },
          {
            "name": "Prioridade Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2a612e3-9e47-40b0-94eb-1901bbb49c77",
            "sourceColumn": "Prioridade Pedido",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b13c490a-13f2-4e7e-b168-2dcf2f2cdccf",
        "partitions": [
          {
            "name": "Pedidos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"D:\\Marcelo Data\\Data_Science_Academy\\PowerBI Para Business Intelligence e Data Science\\3- Modelagem Relacionamentos e DAX\\Pedidos.csv\"),[Delimiter=\";\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID Pedido\", type text}, {\"Data Pedido\", type date}, {\"Data Envio\", type date}, {\"Modo Envio\", type text}, {\"Prioridade Pedido\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4d8febcb-1bed-4c8c-938d-d9416fab50cc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2eca15f8-aac0-4ae0-a478-3fdfd6db36c9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe216fbd-8286-4d4d-ae7e-839befa2b755",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1f045cb8-a265-44a1-bcd8-d5ad9c8838de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "87309278-b73b-4e00-ba33-306c15551caa",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4424fa59-0f44-447e-a9f9-7191893f2432",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fa9849a9-9b90-4d48-9c08-2c32876d1943",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2eca40a-6b6b-4d62-96fe-cb87db347670",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "f2834df5-65a1-48cc-9e57-c96ea75ca3e2",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "6f358b12-5701-4bb0-92a8-a8837683ddc3",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "3242a7db-ae29-41bb-b552-c211b11c9ed7",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "137bee5c-1291-49d5-9dc7-ea80c04196d6",
                "ordinal": 3
              }
            ],
            "lineageTag": "a7872da9-ba17-4fd8-86c0-5ed156a2c227"
          }
        ],
        "isHidden": true,
        "lineageTag": "e1e5e09b-8d44-4de2-80ab-fd428b183d41",
        "partitions": [
          {
            "name": "LocalDateTable_4d8febcb-1bed-4c8c-938d-d9416fab50cc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Pedidos'[Data Pedido])), 1, 1), Date(Year(MAX('Pedidos'[Data Pedido])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_535664b9-f58a-470b-b411-0ab91c57cfa9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4c753027-4500-4b10-9364-341e51f9422f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c50c16e2-f8aa-482c-bed2-672f8aa55d4d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a5515c57-61cf-4f2b-8d9b-44c634b78858",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d9421a18-ee95-4166-a2af-210cd161af74",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7261c0c0-55a0-43e2-a9bc-d67bee0416b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "23adc280-da3d-4d9d-b36b-01a88ef74ed2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bce23fc7-4513-439a-aeda-b8aabb70c61c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "65fd9d67-c70f-41f5-87af-c6b270b6c2cc",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9d2108ca-9b24-4aa2-ad1a-0e5eae58bfb7",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "8cab3b4f-cf39-439b-accb-c959c5bbb337",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8d97c11c-91de-469f-aa57-3f9e413ed440",
                "ordinal": 3
              }
            ],
            "lineageTag": "a0e41661-06ad-4048-873a-101bc5cf3eba"
          }
        ],
        "isHidden": true,
        "lineageTag": "c51670e3-9e35-4d8a-9292-3d300adbf892",
        "partitions": [
          {
            "name": "LocalDateTable_535664b9-f58a-470b-b411-0ab91c57cfa9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Pedidos'[Data Envio])), 1, 1), Date(Year(MAX('Pedidos'[Data Envio])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Produtos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b5fd0bb-357b-4ed8-9363-371b2cbbf71f",
            "sourceColumn": "ID Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6e11f39-6183-4546-a86e-9b858cd5134c",
            "sourceColumn": "Categoria",
            "summarizeBy": "none"
          },
          {
            "name": "SubCategoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1abaee85-f0b2-437a-a007-1fd69634ccd6",
            "sourceColumn": "SubCategoria",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89e0feb5-5191-4971-9eeb-4759bfe481dc",
            "sourceColumn": "Nome Produto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "26938c45-8255-4494-95a4-06fb77343c57",
        "partitions": [
          {
            "name": "Produtos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"D:\\Marcelo Data\\Data_Science_Academy\\PowerBI Para Business Intelligence e Data Science\\3- Modelagem Relacionamentos e DAX\\Produtos.csv\"),[Delimiter=\";\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
                "    #\"Usar primeira linha como cabeçalho\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID Produto\", type text}, {\"Categoria\", type text}, {\"SubCategoria\", type text}, {\"Nome Produto\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Usar primeira linha como cabeçalho\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Vendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a1592ae-25ce-4dc7-b977-63f726cc80b7",
            "sourceColumn": "Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5714032a-8068-449f-9720-fbdcdfc7d723",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ee9b764-746b-4721-9b94-2fde98362aa3",
            "sourceColumn": "Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Valor Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e85e6eb-c21b-4162-8026-2f97eb9b92c7",
            "sourceColumn": "Valor Venda",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantidade Vendida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4bdeac7-d4c8-48e5-8281-505e58e4d0c4",
            "sourceColumn": "Quantidade Vendida",
            "summarizeBy": "sum"
          },
          {
            "name": "Custo Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "990d9e8b-218e-4c6b-8e36-fcf75a6b6323",
            "sourceColumn": "Custo Envio",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "49e74555-49cf-4a94-a4b9-60be2954a015",
        "partitions": [
          {
            "name": "Vendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"D:\\Marcelo Data\\Data_Science_Academy\\PowerBI Para Business Intelligence e Data Science\\3- Modelagem Relacionamentos e DAX\\Vendas.csv\"),[Delimiter=\";\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Pedido\", type text}, {\"Cliente\", type text}, {\"Produto\", type text}, {\"Valor Venda\", type number}, {\"Quantidade Vendida\", Int64.Type}, {\"Custo Envio\", type number}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}